from . import help
from . import start
from . import admin
from . import registratsiya4
from . import registratsiya2
from . import registratsiya3
from . import registratsiya5
from . import registrartsiya6
from . import check
